version: "3"
services:
  web:
    image: nginx:latest
    restart: "no"
    volumes:
      - ./storage/site-content:/usr/share/nginx/html:ro
      - ./storage/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8081:80
  cdn:
    image: varnish:latest
    restart: "no"
    volumes:
      - ./cdn/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - 9000:80